apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-kueue-reader
rules:
  - apiGroups: [ "serving.kserve.io" ]
    resources: [ "inferenceservices" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kserve-kueue-reader
subjects:
  - kind: ServiceAccount
    name: kueue-controller-manager
    namespace: kueue-system
roleRef:
  kind: ClusterRole
  name: kserve-kueue-reader
  apiGroup: rbac.authorization.k8s.io

