apiVersion: v1
kind: Namespace
metadata:
  name: kserve-keda-prom
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: huggingface-fbopt
  namespace: kserve-keda-prom
  annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
    serving.kserve.io/autoscalerClass: "keda"
    serving.kserve.io/enable-prometheus-scraping: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
  labels:
    kueue.x-k8s.io/queue-name: "local-queue"
spec:
  predictor:
    model:
      readinessProbe:
        failureThreshold: 10
        periodSeconds: 10
        successThreshold: 1
        initialDelaySeconds: 120
        tcpSocket:
          port: 8080
        timeoutSeconds: 10
      modelFormat:
        name: huggingface
      args:
        - --model_name=fbopt
        - --model_id=facebook/opt-125m
      resources:
        requests:
          cpu: "4"
          memory: 16Gi
        limits:
          cpu: "4"
          memory: 16Gi
    minReplicas: 1
    maxReplicas: 2
    autoScaling:
      metrics:
        - type: External
          external:
            metric:
              backend: "prometheus"
              serverAddress: "http://kube-prometheus-stack-prometheus.kube-prometheus.svc.cluster.local:9090"
              query: vllm:num_requests_running
            target:
              type: Value
              value: "2"
